/**
 * Configuration Loader
 * Loads and parses config.yaml, provides template string interpolation
 */

// Global configuration object (populated after loading)
let CONFIG_APP = null;

// Default category display order — used as fallback when config.yaml doesn't specify categoryOrder
const DEFAULT_CATEGORY_ORDER = ['Transportation', 'Economic Development', 'Environmental/Cultural'];

/**
 * Interpolates template strings in configuration values
 * Replaces {path.to.value} with actual config values
 * @param {string} str - String potentially containing template variables
 * @param {object} config - Configuration object
 * @returns {string} - Interpolated string
 */
function interpolateTemplate(str, config) {
  if (typeof str !== 'string') return str;

  return str.replace(/\{([^}]+)\}/g, (match, path) => {
    const keys = path.split('.');
    let value = config;

    for (const key of keys) {
      if (value && typeof value === 'object' && key in value) {
        value = value[key];
      } else {
        console.warn(`Template variable not found: ${path}`);
        return match; // Return original if path not found
      }
    }

    if (typeof value !== 'string' && typeof value !== 'number' && typeof value !== 'boolean') {
      console.warn(`config.yaml template {${path}} resolved to a non-scalar (${typeof value}). Returning placeholder unchanged.`);
      return match;
    }
    return String(value);
  });
}

/**
 * Recursively interpolates all string values in an object
 * @param {any} obj - Object to interpolate
 * @param {object} config - Configuration object
 * @returns {any} - Interpolated object
 */
function interpolateObject(obj, config) {
  if (typeof obj === 'string') {
    return interpolateTemplate(obj, config);
  } else if (Array.isArray(obj)) {
    return obj.map(item => interpolateObject(item, config));
  } else if (obj && typeof obj === 'object') {
    const result = {};
    for (const [key, value] of Object.entries(obj)) {
      result[key] = interpolateObject(value, config);
    }
    return result;
  }
  return obj;
}

/**
 * Loads and parses the configuration file
 * @returns {Promise<object>} - Parsed configuration object
 */
async function loadConfig() {
  try {
    // Fetch config.yaml
    const response = await fetch('./config.yaml', { cache: 'no-store' });
    if (!response.ok) {
      throw new Error(`Failed to load config.yaml: ${response.statusText}`);
    }

    const yamlText = await response.text();

    // Parse YAML (using jsyaml library loaded from CDN)
    if (typeof jsyaml === 'undefined') {
      throw new Error('jsyaml library not loaded. Ensure js-yaml is included before config.js');
    }

    let config;
    try {
      config = jsyaml.load(yamlText);
    } catch (yamlError) {
      if (yamlError.name === 'YAMLException') {
        const lineNum = yamlError.mark ? yamlError.mark.line + 1 : '?';
        throw new Error(
          `YAML syntax error in config.yaml at line ${lineNum}:\n${yamlError.reason || yamlError.message}\n\n` +
          `How to fix:\n` +
          `  1. Check line ${lineNum} for missing colons, wrong indentation, or stray characters\n` +
          `  2. Validate your file at https://www.yamllint.com/\n` +
          `  3. Indentation must use spaces, not tabs`
        );
      }
      throw yamlError;
    }

    // Validate required fields
    if (!config.organization || !config.organization.name) {
      throw new Error('config.yaml missing required field: organization.name');
    }
    if (!config.geography || !config.geography.mapBounds) {
      throw new Error('config.yaml missing required field: geography.mapBounds');
    }

    // Interpolate all template strings
    const interpolated = interpolateObject(config, config);

    // Store in global
    CONFIG_APP = interpolated;
    window.CONFIG_APP = CONFIG_APP;

    console.log('Configuration loaded successfully:', CONFIG_APP);
    return CONFIG_APP;

  } catch (error) {
    console.error('Error loading configuration:', error);

    // Provide fallback defaults so app doesn't crash
    // Uses continental US centroid and bounds as a true generic fallback
    CONFIG_APP = {
      organization: {
        name: 'Metropolitan Planning Organization',
        shortName: 'MPO',
        planName: 'Regional Transportation Plan',
        planYear: '2050'
      },
      branding: {
        pageTitle: 'MPO Project Application Tool',
        headerYear: 'RTP',
        logoPath: './assets/logo.png',
        pdfFooter: 'Generated by MPO Project Application Tool',
        pdfDisclaimer: 'For preliminary analysis'
      },
      geography: {
        mapBounds: {
          southwest: [24, -125],
          northeast: [50, -66]
        },
        validationBounds: {
          minLng: -125,
          maxLng: -66,
          minLat: 24,
          maxLat: 50
        },
        defaultZoom: 4
      },
      categoryOrder: ['Transportation', 'Economic Development', 'Environmental/Cultural'],
      mapStyling: {
        basemapUrl: 'https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png',
        basemapAttribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>',
        drawnLine: { color: '#FF0000', weight: 12, opacity: 0.9 },
        measurementLine: { color: '#FF8C00', weight: 4, opacity: 0.8, dashArray: '8, 8' }
      }
    };

    AppUtils.showError('Failed to load configuration file. Using default settings.\n\nError: ' + error.message);
    return CONFIG_APP;
  }
}

// Export for use in other modules
window.CONFIG_APP = CONFIG_APP;
window.loadConfig = loadConfig;
